#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  shift; shift

  unset BUNDLER_ORIG_BUNDLE_GEMFILE GEM_HOME BUNDLE_GEMFILE

  cd "$phome"
  local nm_block="${phome##*/}"

  if [[ -f "${BOARD_PATH}/Gemfile.lock.${nm_block}" ]]; then
    ln -nfs "${BOARD_PATH}/Gemfile.lock.${nm_block}" "Gemfile.lock"
  fi

  set -x

  if [[ "$#" == 0 ]]; then
    set -- install --path "$phome/vendor" --binstubs "$phome/vendor/bundle/bin" "$@"
  fi

  if [[ "${1:-}" == "update" ]]; then
    bundle update
  else
    bundle "$@"
  fi

  if [[ ! -L Gemfile.lock ]]; then
    rsync -ia Gemfile.lock "${BOARD_PATH}/Gemfile.lock.${nm_block}"
  fi
  ln -nfs "${BOARD_PATH}/Gemfile.lock.${nm_block}" "Gemfile.lock"
}

source sub "$0" "$@"
