#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  shift; shift

  cd "$phome"
  local nm_block="${phome##*/}"

  if [[ -f "${BOARD_PATH}/Gemfile.lock.${nm_block}" ]]; then
    ln -nfs "${BOARD_PATH}/Gemfile.lock.${nm_block}" "Gemfile.lock"
  fi

  if [[ "$#" == 0 ]]; then
    set -- install --deployment --local --binstubs "$phome/vendor/bundle/bin" "$@"
  fi

  bundle "$@"

  if [[ ! -L Gemfile.lock ]]; then
    rsync -ia Gemfile.lock "${BOARD_PATH}/Gemfile.lock.${nm_block}"
  fi
  ln -nfs "${BOARD_PATH}/Gemfile.lock.${nm_block}" "Gemfile.lock"
}

source sub "$0" "$@"
