#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure lang/ruby22-base
  pkg ensure ruby22-gdbm databases/ruby-gdbm
  pkg ensure ruby22-readline devel/ruby-readline
  gem install bundler
}

bootstrap
