#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ !  -x "$(which ruby22 2>/dev/null || true)" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
