#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if type -P rbenv >/dev/null; then
    return 0
  fi

  if [[ !  -x "$(which "ruby${RUBY_VERSION}" 2>/dev/null || true)" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.bundler')" != "$BUNDLER_VERSION" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
