#!/usr/bin/env bash

function _ruby_profile {
  local shome="${_ruby_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  PATH="${BOARD_PATH}/.rbenv/shims:$PATH"

  RUBY_VERSION='23'
  GEM_VERSION='2.6.13'
  export BUNDLER_VERSION='1.15.4'
}

_ruby_profile
