#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$(rbenv version-name 2>/dev/null)" == "$(ruby -e 'puts RUBY_VERSION')" ]]; then
    if [[ -x "$(which bundle 2>/dev/null || true)" ]]; then
      return 1
    fi
  fi

  return 0
}

source sub "$0" "$@"
