#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$shome/.rbenv/versions/$(rbenv version-name 2>/dev/null)/bin/ruby" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
