#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_ruby="$(ruby --version 2>&- | awk 'NR == 1 {print $2}')"
  local ver_rbenv="$(rbenv --version 2>&- | awk 'NR == 1 {print $2}')"
  local ver_rubybuild="$(ruby-build --version 2>&- | awk 'NR == 1 {print $2}')"
  local ver_bundler="$(bundle --version 2>&- | awk 'NR == 1 {print $3}')"
  jq -n \
    --arg ruby "$ver_ruby" \
    --arg rbenv "$ver_rbenv" \
    --arg rubybuild "$ver_rubybuild" \
    --arg bundler "$ver_bundler" \
    '{ruby: $ruby, rbenv: $rbenv, "ruby-build": $rubybuild, bundler: $bundler}'
}

version "$@"
